services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-espacos-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=espacos_corporativos
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: gestao-espacos-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=espacos_corporativos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/criar_banco.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
